/*
 * This source file was generated by the Gradle 'init' task
 */
package tubes;

import tubes.views.AdminView;
import tubes.utils.EmailSender;
import tubes.views.CustomerView;
import tubes.views.ManagerView;
import tubes.views.UserView;


public class App {
    public static void main(String[] args) {
        // UserView start = new UserView();
        // start.showMenuLogin();

        // ManagerView test = new ManagerView();
        // test.showMainMenu();

        CustomerView test = new CustomerView(true);
        test.startCustomerView();

    }
    
}
