/*
 * This source file was generated by the Gradle 'init' task
 */
package tubes;

import tubes.views.AdminView;
// import tubes.views.CustomerView;
import tubes.views.UserView;


public class App {
    public static void main(String[] args) {
        UserView start = new UserView();
        start.showMenuLogin();

        // CustomerView test = new CustomerView();
        // test.showMoviesList();

        // AdminView admin = new AdminView();
    }
}
