/*
 * This source file was generated by the Gradle 'init' task
 */
package tubes;

import tubes.views.CustomerView;
import tubes.views.LoginUI;

public class App {
    public static void main(String[] args) {
        // LoginUI start = new LoginUI();
        // start.showMenuLogin();

        CustomerView test = new CustomerView(true);
        test.startCustomerView();
    }
}
